### PR TITLE
clippy + rustfmt

### PR DESCRIPTION
**Pull request by sn99**
Made a few tweaks to the code that do not change the end product. Though a few points
1. In `src/graph.rs` a `Default` implementation for `graph::Graph<T>` can be better (using `#[derive(Default)]`)
2. In `src/iterators/dfs` on line 34 the loop does not really loop, it breaks after one loop

### CODE REVIEW

**Comment by octavonce** [comment]
Thank you for opening the PR!

Yes, we can add a default implementation for sure!

The loop on line 34 is just a hack to get one random `VertexId`, this should be changed with #2 when we will traverse based on weight.

**Comment by sn99** [comment]
@octavonce  Ah my bad, the `graph` struct uses `Hashmap` from `hashbrown` crate not the `std` one, `Default` does not seem great then

**Comment by octavonce** [comment]
@sn99 Can you expand a bit on this? Why is it good for the std version and not so great for hashbrown?

From my point of view we can extend the api with a default implementation just for completeness. But I also believe that the extensions in #7 are more beneficial.

Also, can you please rebase your branch with master so we can merge this? We can open a new issue to discuss the default dilemma further if necessary.

**Comment by sn99** [comment]
@octavonce Hashbrown might use it own abstraction and may change with time whereas std has defined roles for [default](https://doc.rust-lang.org/std/default/trait.Default.html) also Default is not recursive in nature ([this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=51f5afc1e3c2d3f561f5f077e6787f3f) does not compile), #7 seems interesting to work on though

**Review by octavonce — APPROVED** [review]

**Comment by octavonce** [comment]
@sn99 Ok, this makes sense. We can keep the implementation like this so far and focus on #7 and maybe when hashbrown has better support for this we can add a derive.

Feel free to merge

**Comment by sn99** [comment]
@octavonce I don't think I have write access to merge it you can merge it though

**Pull request merged**
