### PR TITLE
fix: Add capacity api #7

### PR DESCRIPTION
**Pull request by sn99**
fixex #7, though a few points -

1. Cannot implement `Graph::shrink_to()` in stable rust (currently only possible in nightly)
2. Cannot implement `Graph::reserve_exact()` as [Hashbrown](https://docs.rs/hashbrown/0.1.8/hashbrown/struct.HashMap.html#method.reserve) cannot implement `reserve_exact`

Was able to complete all others with complete documentation and example

I also added `capacity_v()` to give more verbose result about `Graph` capacity complete with example and documentation

### CODE REVIEW

**Comment by octavonce** [comment]
This looks good! Just two things:
* I don't see a reason for having a verbose capacity method. Unless there is a very concrete and specific reason for why we should include one I believe it complicates the api.
* We should move the `min!` macro to a separate macros.rs file for better code organization.

**Comment by sn99** [comment]
when we use `capacity` with  `with_capacity(5)` we get `5` but `capacity_v` returns `7,5,5,7,7` (more correct info) due to `Hasbrown` implementation, also it may be possible that a user might try to do something clever with only one of the fields of the struct `Graph` and might require `capacity_v` later, I will remove it if you want though

**Comment by octavonce** [comment]
I think it's best we leave it out for now. We can always add it later if necessary.

**Comment by sn99** [comment]
removed it

**Comment by octavonce** [comment]
I was thinking, there are two capacities we care about: the vertices capacity and the edges capacity. Both of these can be completely different. We could offer a separate api for setting the edge capacity but I believe it would confuse the user.

Another solution would be to simply set the capacity of the edges vector to that of n^2 where n is the vertex capacity since there are no duplicate edges allowed and the api would remain the same it is now.

**Comment by sn99** [comment]
Second point seems more resonable

> capacity of the edges vector to that of n^2

Is it n^2 or n*2 ?

**Comment by octavonce** [comment]
It's n^2 because every vertex can have an edge between it and every other vertex in the graph, in both directions.

Let's suppose we have a 3 element graph that has every possible edge between its vertices listed, including itself. If we note the vertices as A, B and C we get the following unique pairs:

1) A -> A
2) A -> B
3) A -> C
4) B -> A
5) B -> B
6) B -> C
7) C -> A
8) C -> B
9) C -> C

Total is 9 possible edges which is 3^2.

**Comment by sn99** [comment]
@octavonce done

**Review by octavonce — APPROVED** [review]
Looks good! Merging now.

**Pull request merged**
